# Generated by Django 4.2.7 on 2024-01-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="img_url",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(default="image", upload_to="media/"),
            preserve_default=False,
        ),
    ]
