# Generated by Django 5.0.1 on 2024-01-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_blogpost_img_url_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="estimated_read_time",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
